[build]
  publish = "public/"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# [[plugins]]
# package = "netlify-plugin-cache"
#   [plugins.inputs]
#   paths = ["elm-stuff"]